#!/usr/bin/env python3
"""Regenerates the Blendshape V2 Golden A fixture used by
integration_test/blendshapes_integration_test.dart.

It downloads MediaPipe's official standalone blendshape golden (an input
landmark set and the expected classification scores), packs the input the same
way the deployed graph does, and runs the bundled face_blendshapes.tflite with
the TFLite reference interpreter to confirm it reproduces the expected output
before writing the Dart fixture.

Key finding baked in here: the model is invariant to a uniform scale of the
input landmarks (it re-normalizes internally), but NOT to aspect ratio. The
official graph feeds pixel coordinates (normalized landmark * image size), so
the source image's real dimensions matter. MediaPipe's portrait.jpg is
820x1024; scaling by those dimensions reproduces face_blendshapes_out.prototxt
to < 2e-6. This is also why the package pipeline is correct: it packs real
pixel coordinates, which carry the true aspect ratio.

Usage (from repo root):
    python3 example/tool/gen_blendshapes_golden.py

Requires: numpy, tensorflow (for tf.lite.Interpreter), and network access.
"""

import re
import ssl
import urllib.request

import numpy as np
from tensorflow.lite.python.interpreter import Interpreter

BASE = (
    "https://raw.githubusercontent.com/google-ai-edge/mediapipe/master/"
    "mediapipe/tasks/testdata/vision"
)
MODEL = "assets/models/face_blendshapes.tflite"
OUT = "example/integration_test/blendshapes_golden_data.dart"

# portrait.jpg (the source image for the golden landmarks) is 820x1024.
IMG_W, IMG_H = 820, 1024

# The 146-landmark subset, verbatim from face_blendshapes_graph.cc.
SUBSET = [
    0, 1, 4, 5, 6, 7, 8, 10, 13, 14, 17, 21, 33, 37, 39, 40, 46, 52, 53, 54, 55,
    58, 61, 63, 65, 66, 67, 70, 78, 80, 81, 82, 84, 87, 88, 91, 93, 95, 103, 105,
    107, 109, 127, 132, 133, 136, 144, 145, 146, 148, 149, 150, 152, 153, 154, 155,
    157, 158, 159, 160, 161, 162, 163, 168, 172, 173, 176, 178, 181, 185, 191, 195,
    197, 234, 246, 249, 251, 263, 267, 269, 270, 276, 282, 283, 284, 285, 288, 291,
    293, 295, 296, 297, 300, 308, 310, 311, 312, 314, 317, 318, 321, 323, 324, 332,
    334, 336, 338, 356, 361, 362, 365, 373, 374, 375, 377, 378, 379, 380, 381, 382,
    384, 385, 386, 387, 388, 389, 390, 397, 398, 400, 402, 405, 409, 415, 454, 466,
    468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
]


def fetch(name: str) -> str:
    url = f"{BASE}/{name}"
    try:
        with urllib.request.urlopen(url) as r:
            return r.read().decode()
    except urllib.error.URLError:
        # Some Python installs (e.g. macOS python.org builds) lack a configured
        # CA bundle. This only fetches public MediaPipe test fixtures, so fall
        # back to an unverified context.
        ctx = ssl._create_unverified_context()
        with urllib.request.urlopen(url, context=ctx) as r:
            return r.read().decode()


def main() -> None:
    in_txt = fetch("face_blendshapes_in_landmarks.prototxt")
    out_txt = fetch("face_blendshapes_out.prototxt")

    lms = [
        (
            float(re.search(r"x:\s*([-\d.e]+)", b).group(1)),
            float(re.search(r"y:\s*([-\d.e]+)", b).group(1)),
        )
        for b in re.findall(r"landmark\s*\{([^}]*)\}", in_txt)
    ]
    expected = [
        float(re.search(r"score:\s*([-\d.e]+)", b).group(1))
        for b in re.findall(r"classification\s*\{([^}]*)\}", out_txt)
    ]

    packed = []
    for idx in SUBSET:
        packed += [lms[idx][0] * IMG_W, lms[idx][1] * IMG_H]

    itp = Interpreter(model_path=MODEL)
    itp.allocate_tensors()
    ind, outd = itp.get_input_details()[0], itp.get_output_details()[0]
    itp.set_tensor(ind["index"], np.array(packed, np.float32).reshape(1, 146, 2))
    itp.invoke()
    got = itp.get_tensor(outd["index"]).reshape(-1)
    err = float(np.max(np.abs(got[:52] - np.array(expected))))
    print(f"reference reproduction max abs error: {err:.2e}")
    assert err < 1e-4, "model does not reproduce the golden; refusing to write"

    def block(vals):
        rows = [
            ", ".join(f"{v:.6f}" for v in vals[i : i + 8])
            for i in range(0, len(vals), 8)
        ]
        return ",\n  ".join(rows)

    with open(OUT, "w") as f:
        f.write(
            "// Generated by example/tool/gen_blendshapes_golden.py. Do not edit.\n"
            "//\n"
            "// Golden fixture for the MediaPipe Blendshape V2 model, derived from the\n"
            "// official MediaPipe testdata (face_blendshapes_in_landmarks.prototxt +\n"
            "// face_blendshapes_out.prototxt, portrait.jpg 820x1024). The input is the\n"
            "// 146-landmark subset packed as x,y pixel pairs (normalized * 820/1024);\n"
            "// the expected output is MediaPipe's own classification scores, reproduced\n"
            "// by the TFLite reference interpreter to < 2e-6.\n"
            "const List<double> kGoldenBlendshapeInput = <double>[\n  "
            + block(packed)
            + ",\n];\n\n"
            "const List<double> kGoldenBlendshapeExpected = <double>[\n  "
            + block(expected)
            + ",\n];\n"
        )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
